export const ALL_COMPANIES: string[] = [
    "All Service Gebäudedienste GmbH",
    "Allessa GmbH",
    "AllessaProduktion GmbH",
    "Apleona GmbH",
    "Auto-Service Safar GmbH",
    "Berger & Sohn GmbH",
    "Berggold GmbH",
    "Biomasse-Kraftwerk Fechenheim GmbH",
    "BioSpring GmbH",
    "C.I.S. City Industrie Service GmbH",
    "CCF Cassella Chemiepark Frankfurt GmbH",
    "Corden Pharma Germany GmbH",
    "Dillenberger GmbH",
    "Erich Köhler GmbH",
    "G+H ISOLIERUNG GmbH",
    "Geohumus GmbH",
    "GESTA Gesellschaft für Stahlrohrgerüste mbH",
    "GETEC GmbH",
    "Helmut Haug GmbH",
    "ICIG Business Services GmbH",
    "IFÜREL EMSR-Technik GmbH & Co. KG",
    "Infraserv Logistics GmbH",
    "INTU Bau GmbH",
    "KBR Planungsgesellschaft mbH",
    "KNETTENBRECH + GURDULIC Service GmbH & Co. KG",
    "Landmann & Walter Kältetechnik GmbH",
    "LGA Immissions- und Arbeitsschutz GmbH",
    "Mainova AG",
    "people at work Personalleasing GmbH",
    "Piepenbrock Service GmbH + Co. KG",
    "Prefere Melamines GmbH",
    "Randstad Deutschland GmbH & Co. KG",
    "Renault Retail Group Deutschland GmbH",
    "RevLabs GmbH",
    "ROHRER Industrieservice GmbH",
    "Schneider + Partner GmbH",
    "Siemens AG",
    "Sonepar Deutschland GmbH",
    "Spano GmbH",
    "Stahlbau Franz GmbH",
    "STRABAG SE",
    "Suffel Fördertechnik GmbH & Co. KG",
    "TKB-Kellner GmbH",
    "TÜV Technische Überwachung Hessen GmbH",
    "UMTEC GmbH",
    "Union Glas- und Gebäudereinigung GmbH",
    "VELTEC GmbH & Co. KG",
    "Weber Rohrleitungsbau GmbH & Co. KG",
    "Werner Reitz GmbH",
    "Werner Umweltservice GmbH",
    "WeylChem InnoTec GmbH",
    "WeylChem International GmbH",
    "WISA"
];

export const FREQUENTLY_USED_COMPANIES: string[] = [
    "CCF Cassella Chemiepark Frankfurt GmbH",
    "AllessaProduktion GmbH",
    "Allessa GmbH",
    "BioSpring GmbH",
    "Corden Pharma Germany GmbH",
    "Prefere Melamines GmbH"
];
